/* Copyright 2016 Streampunk Media Ltd

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

/* -LICENSE-START-
 ** Copyright (c) 2010 Blackmagic Design
 **
 ** Permission is hereby granted, free of charge, to any person or organization
 ** obtaining a copy of the software and accompanying documentation covered by
 ** this license (the "Software") to use, reproduce, display, distribute,
 ** execute, and transmit the Software, and to prepare derivative works of the
 ** Software, and to permit third-parties to whom the Software is furnished to
 ** do so, all subject to the following:
 **
 ** The copyright notices in the Software and this entire statement, including
 ** the above license grant, this restriction and the following disclaimer,
 ** must be included in all copies of the Software, in whole or in part, and
 ** all derivative works of the Software, unless such copies or derivative
 ** works are solely in the form of machine-executable object code generated by
 ** a source language processor.
 **
 ** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 ** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 ** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 ** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 ** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 ** DEALINGS IN THE SOFTWARE.
 ** -LICENSE-END-
 */

#include "stdafx.h"
#include <gl/gl.h>
#include "Preview.h"


namespace streampunk {

inline Nan::Persistent<v8::Function> &Preview::constructor() {
  static Nan::Persistent<v8::Function> myConstructor;
  return myConstructor;
}

Preview::Preview(uint32_t displayMode, uint32_t pixelFormat)
 : m_refCount(1), m_deckLinkScreenPreviewHelper(NULL), m_openGLctx(NULL),
     displayMode_(displayMode), pixelFormat_(pixelFormat) {}

Preview::~Preview() {
  if (m_deckLinkScreenPreviewHelper != NULL) {
    m_deckLinkScreenPreviewHelper->Release();
    m_deckLinkScreenPreviewHelper = NULL;
  }

  if (m_openGLctx != NULL) {
    wglDeleteContext(m_openGLctx);
    m_openGLctx = NULL;
  }
}

NAN_MODULE_INIT(Preview::Init) {
  #ifdef WIN32
  HRESULT result;
  result = CoInitialize(NULL);
	if (FAILED(result))
	{
		fprintf(stderr, "Initialization of COM failed - result = %08x.\n", result);
	}
  #endif

  // Prepare constructor template
  v8::Local<v8::FunctionTemplate> tpl = Nan::New<v8::FunctionTemplate>(New);
  tpl->SetClassName(Nan::New("Preview").ToLocalChecked());
  tpl->InstanceTemplate()->SetInternalFieldCount(1);

  // Prototype
  Nan::SetPrototypeMethod(tpl, "init", BMInit);
  Nan::SetPrototypeMethod(tpl, "drawNext", DrawNext);
  Nan::SetPrototypeMethod(tpl, "stop", Stop);

  constructor().Reset(Nan::GetFunction(tpl).ToLocalChecked());
  Nan::Set(target, Nan::New("Preview").ToLocalChecked(),
               Nan::GetFunction(tpl).ToLocalChecked());
}

NAN_METHOD(Preview::New) {
  if (info.IsConstructCall()) {
    // Invoked as constructor: `new Preview(...)`
    uint32_t displayMode = info[1]->IsUndefined() ? 0 : Nan::To<uint32_t>(info[1]).FromJust();
    uint32_t pixelFormat = info[2]->IsUndefined() ? 0 : Nan::To<uint32_t>(info[2]).FromJust();
    Preview* obj = new Preview(displayMode, pixelFormat);
    obj->Wrap(info.This());
    info.GetReturnValue().Set(info.This());
  } else {
    // Invoked as plain function `Preview(...)`, turn into construct call.
    const int argc = 2;
    v8::Local<v8::Value> argv[argc] = { info[0], info[1] };
    v8::Local<v8::Function> cons = Nan::New(constructor());
    info.GetReturnValue().Set(Nan::NewInstance(cons, argc, argv).ToLocalChecked());
  }
}

NAN_METHOD(Preview::BMInit) { }
NAN_METHOD(Preview::DrawNext) { }
NAN_METHOD(Preview::Stop) { }

HRESULT Preview::QueryInterface(REFIID iid, LPVOID *ppv) {
  *ppv = NULL;
  return E_NOINTERFACE;
}

ULONG Preview::AddRef() {
  return InterlockedIncrement((LONG*) &m_refCount);
}

ULONG Preview::Release() {
  ULONG newRefValue;

  newRefValue = InterlockedDecrement((LONG*) &m_refCount);
  if (newRefValue == 0) {
    delete this;
    return 0;
  }
}

HRESULT Preview::DrawFrame(IDeckLinkVideoFrame* theFrame) {

}

} // Namespace streampunk
